---

- hosts: localhost
  connection: local
  become: true
  vars:
      is_container: false
  roles:
  - role: "{{ playbook_dir }}"
    rhel7cis_system_is_container: "{{ is_container | default(false) }}"
    rhel7cis_ssh_required: "{{ is_container == false  }}"
