---
- name: "PRELIM | {{ rhel7cis_passwd_tasks }} | Parse /etc/passwd"
  block:
  - name: "PRELIM | {{ rhel7cis_passwd_tasks }} | Parse /etc/passwd"
    command: egrep -v '^(\s*#|\s+|$)' /etc/passwd
    changed_when: false
    check_mode: false
    register: rhel7cis_passwd_file_audit

  - name: "PRELIM | {{ rhel7cis_passwd_tasks }} | Split passwd entries"
    set_fact:
        rhel7cis_passwd: "{{ rhel7cis_passwd_file_audit.stdout_lines | map('regex_replace', ld_passwd_regex, ld_passwd_yaml) | map('from_yaml') | list }}"
    with_items: "{{ rhel7cis_passwd_file_audit.stdout_lines }}"
    vars:
        ld_passwd_regex: >-
            ^(?P<id>[^:]*):(?P<password>[^:]*):(?P<uid>[^:]*):(?P<gid>[^:]*):(?P<gecos>[^:]*):(?P<dir>[^:]*):(?P<shell>[^:]*)
        ld_passwd_yaml: |
            id: >-4
                \g<id>
            password: >-4
                \g<password>
            uid: \g<uid>
            gid: \g<gid>
            gecos: >-4
                \g<gecos>
            dir: >-4
                \g<dir>
            shell: >-4
                \g<shell>
  tags:
  - always
