---

- name: "5.2.1 | PATCH | Ensure sudo is installed"
  package:
      name: sudo
      state: present
  become: true
  when:
      - rhel7cis_rule_5_2_1
  tags:
      - level1-server
      - level1-workstation
      - sudo
      - patch
      - rule_5.2.1
  vars:
      ansible_python_interpreter: /bin/python

- name: "5.2.2 | AUDIT | Ensure sudo commands use pty"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    use_pty'
      line: 'Defaults    use_pty'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
  become: true
  when:
      - rhel7cis_rule_5_2_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - sudo
      - rule_5.2.2

- name: "5.2.3 | PATCH | Ensure sudo log file exists"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    logfile="{{ rhel7cis_varlog_location }}"'
      line: 'Defaults    logfile="{{ rhel7cis_varlog_location }}"'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
  become: true
  when:
      - rhel7cis_rule_5_2_1 and rhel7cis_rule_5_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - sudo
      - rule_5.2.3
