---

- name: "5.3.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600
  when:
      - rhel7cis_rule_5_3_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.1

- name: "5.3.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
      - name: "5.3.2 | AUDIT | Ensure permissions on SSH private host key files are configured"
        find:
            paths:
                - /etc/ssh
            patterns: 'ssh_host_*_key'
            recurse: true
            file_type: any
        register: rhel_07_5_3_2_priv_results

      - name: "5.3.2 | AUDIT | Ensure permissions on SSH private host key files are configured"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0600
        loop: "{{ rhel_07_5_3_2_priv_results.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rhel7cis_rule_5_3_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.2

- name: "5.3.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
      - name: "5.3.3 | AUDIT | Ensure permissions on SSH public host key files are configured"
        find:
            paths:
                - /etc/ssh
            patterns: 'ssh_host_*_key'
            recurse: true
            file_type: any
        register: rhel_07_5_3_3_pub_results

      - name: "5.3.3 | AUDIT | Ensure permissions on SSH public host key files are configured"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0600
        loop: "{{ rhel_07_5_3_3_pub_results.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rhel7cis_rule_5_3_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.3

- name: "5.3.4 | PATCH | Ensure SSH access is limited"
  block:
      - name: "5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^AllowUsers"
            insertbefore: "# Accept locale-related environment variables"
            line: AllowUsers {{ rhel7cis_sshd['allowusers'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "rhel7cis_sshd['allowusers']|default('') | length > 0"

      - name: "5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowgroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^AllowGroups"
            insertbefore: "# Accept locale-related environment variables"
            line: AllowGroups {{ rhel7cis_sshd['allowgroups'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "rhel7cis_sshd['allowgroups']|default('') | length > 0"

      - name: "5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denyusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^DenyUsers"
            insertbefore: "# Accept locale-related environment variables"
            line: DenyUsers {{ rhel7cis_sshd['denyusers'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "rhel7cis_sshd['denyusers']|default('') | length > 0"

      - name: "5.3.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denygroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^DenyGroups"
            insertbefore: "# Accept locale-related environment variables"
            line: DenyGroups {{ rhel7cis_sshd['denygroups'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "rhel7cis_sshd['denygroups']|default('') | length > 0"
  when:
      - rhel7cis_rule_5_3_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.4

- name: "5.3.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#LogLevel|^LogLevel"
      line: 'LogLevel {{ rhel7cis_ssh_loglevel }}'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.5

- name: "5.3.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#X11Forwarding|^X11Forwarding"
      line: 'X11Forwarding no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_6
  tags:
      - level2-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.6

- name: "5.3.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxAuthTries \d'
      line: 'MaxAuthTries 4'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_7
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.7

- name: "5.3.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#IgnoreRhosts|^IgnoreRhosts"
      line: 'IgnoreRhosts yes'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_8
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.8

- name: "5.3.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#HostbasedAuthentication|^HostbasedAuthentication"
      line: 'HostbasedAuthentication no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_9
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.9

- name: "5.3.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#PermitRootLogin|^PermitRootLogin"
      line: 'PermitRootLogin no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_10
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.10

- name: "5.3.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#PermitEmptyPasswords|^PermitEmptyPasswords"
      line: 'PermitEmptyPasswords no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_11
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.11

- name: "5.3.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#PermitUserEnvironment|^PermitUserEnvironment"
      line: 'PermitUserEnvironment no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_12
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.12

- name: "5.3.13 | PATCH | Ensure only strong Ciphers are used"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Ciphers'
      insertbefore: "# Accept locale-related environment variables"
      line: "Ciphers {{ rhel7cis_sshd['ciphers'] }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_13
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.13

- name: "5.3.14 | PATCH | Ensure only strong MAC algorithms are used"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^MACs'
      insertbefore: "# Accept locale-related environment variables"
      line: "MACs {{ rhel7cis_sshd['macs'] }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_14
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.14

- name: "5.3.15 | PATCH | Ensure only strong Key Exchange algorithms are used"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^KexAlgorithms'
      line: "KexAlgorithms {{ rhel7cis_sshd['kex'] }}"
      insertafter: '^MACs'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_15
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.15

- name: "5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
      - name: "5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^#ClientAliveInterval|^ClientAliveInterval"
            line: "ClientAliveInterval {{ rhel7cis_sshd['clientaliveinterval'] }}"
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd

      - name: "5.3.16 | PATCH | Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^#ClientAliveCountMax|^ClientAliveCountMax"
            line: "ClientAliveCountMax {{ rhel7cis_sshd['clientalivecountmax'] }}"
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
  when:
      - rhel7cis_rule_5_3_16
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.16

- name: "5.3.17 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#LoginGraceTime|^LoginGraceTime"
      line: "LoginGraceTime {{ rhel7cis_sshd['logingracetime'] }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_17
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.17

- name: "5.3.18 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^Banner ((?!/etc/issue.net$)).*$'
      line: "{{ item.line | default (omit) }}"
      insertafter: "{{ item.after | default(omit) }}"
      state: "{{ item.state }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  with_items:
      - { state: absent }
      - { state: present, line: 'Banner /etc/issue.net', after: '#Banner none' }
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_18
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.18

- name: "5.3.19 | PATCH | Ensure SSH PAM is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#UsePAM|^UsePAM"
      line: 'UsePAM yes'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_19
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.19

- name: "5.3.20 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#AllowTcpForwarding|^AllowTcpForwarding"
      line: 'AllowTcpForwarding no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_20
  tags:
      - level2-server
      - level2-workstation
      - patch
      - ssh
      - rule_5.3.20

- name: "5.3.21 | PATCH | Ensure SSH MaxStartups is configured"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#MaxStartups|^MaxStartups"
      line: 'MaxStartups 10:30:60'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_21
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.21

- name: "5.3.22 | PATCH | Ensure SSH MaxSessions is limited"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#MaxSessions|^MaxSessions"
      line: 'MaxSessions {{ rhel7cis_ssh_maxsessions }}'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rhel7cis_rule_5_3_22
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.3.22
