---
 
- name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted"
  block:
  - name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted | Setting pm_wheel to use_uid"
    lineinfile:
      state: present
      dest: /etc/pam.d/su
      regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
      line: 'auth            required        pam_wheel.so use_uid group=sugroup'
    when:
    - rhel7cis_rule_5_6
    tags:
    - level1
    - patch
    - rule_5.6
 
  - name: "SCORED | 5.6 | PATCH | Ensure access to the su command is restricted | create sugroup"
    group:
      name: sugroup
      state: present
  when:
  - rhel7cis_rule_5_6
  tags:
  - level1
  - patch
  - rule_5.6
