---

- name: "5.1.1.1 | PATCH | Ensure rsyslog installed"
  when:
      - "'rsyslog' not in ansible_facts.packages"
      - rhel7cis_rule_5_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - NIST800-53R5_AU-2
      - NIST800-53R5_AU-12
      - NIST800-53R5_SI-5
      - rule_5.1.1.1
  ansible.builtin.package:
      name: rsyslog
      state: present

- name: "5.1.1.2 | PATCH | Ensure rsyslog service is enabled"
  when:
      - rhel7cis_rule_5_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - NIST800-53R5_AU-3
      - NIST800-53R5_AU-12
      - rule_5.1.1.2
  ansible.builtin.systemd:
      name: rsyslog
      enabled: true

- name: "5.1.1.3 | PATCH | Ensure journald is configured to send logs to rsyslog"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^#ForwardToSyslog=|^ForwardToSyslog="
      line: ForwardToSyslog=yes
  notify: Restart_journald
  when:
      - rhel7cis_rule_5_1_1_3
      - rhel7cis_syslog == "rsyslog"
  tags:
      - level1-server
      - level1-workstation
      - patch
      - NIST800-53R5_AC-3
      - NIST800-53R5_AU-2
      - NIST800-53R5_AU-4
      - NIST800-53R5_AU-12
      - NIST800-53R5_MP-2
      - NIST800-53R5_SI-5
      - rsyslog
      - rule_5.1.1.3

- name: "5.1.1.4 | PATCH | Ensure rsyslog default file permissions configured"
  when:
      - rhel7cis_rule_5_1_1_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - rule_5.1.1.4
  notify: Restart_rsyslog
  ansible.builtin.lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'

- name: "5.1.1.5 | PATCH | Ensure logging is configured"
  when:
      - rhel7cis_rule_5_1_1_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - rule_5.1.1.5
  notify: Restart_rsyslog
  block:
      - name: "5.1.1.5 | AUDIT | Ensure logging is configured | rsyslog current config message out"
        ansible.builtin.shell: cat /etc/rsyslog.conf
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel7cis_5_1_1_5_audit

      - name: "5.1.1.5 | AUDIT | Ensure logging is configured | rsyslog current config message out"
        ansible.builtin.debug:
            msg:
                - "These are the current logging configurations for rsyslog, please review:"
                - "{{ rhel7cis_5_1_1_5_audit.stdout_lines }}"

      - name: "5.1.1.5 | PATCH | Ensure logging is configured | mail.* log setting"
        when: rhel7cis_rsyslog_ansiblemanaged
        ansible.builtin.blockinfile:
            path: /etc/rsyslog.conf
            marker: "# {mark} MAIL LOG SETTINGS - CIS benchmark - Ansible-lockdown"
            block: |
              # mail logging additions to meet CIS standards
              mail.*                                                  -/var/log/mail
              mail.info                                               -/var/log/mail.info
              mail.warning                                            -/var/log/mail.warning
              mail.err                                                /var/log/mail.err
            insertafter: '# Log all the mail messages in one place.'

      - name: "5.1.1.5 | PATCH | Ensure logging is configured | Misc. log setting"
        when: rhel7cis_rsyslog_ansiblemanaged
        ansible.builtin.blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "# {mark} MISC. LOG SETTINGS - CIS benchmark - Ansible-lockdown"
            block: |
              # misc. logging additions to meet CIS standards
              *.=warning;*.=err                                        -/var/log/warn
              *.crit                                                   /var/log/warn
              *.*;mail.none;news.none                                  /var/log/messages
            insertafter: '#### RULES ####'

      - name: "5.1.1.5 | PATCH | Ensure logging is configured | Local log settings"
        ansible.builtin.blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "#{mark} LOCAL LOG SETTINGS - CIS benchmark - Ansible-lockdown"
            block: |
              # local log settings to meet CIS standards
              local0,local1.*                                          -/var/log/localmessages
              local2,local3.*                                          -/var/log/localmessages
              local4,local5.*                                          -/var/log/localmessages
              local6,local7.*                                          -/var/log/localmessages
              *.emerg                                                    :omusrmsg:*
            insertafter: '#### RULES ####'

      - name: "5.1.1.5 | PATCH | Ensure logging is configured | Auth Settings"
        ansible.builtin.blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "#{mark} Auth SETTINGS - CIS benchmark - Ansible-lockdown"
            block: |
              # Private settings to meet CIS standards
              auth,authpriv.*                                           /var/log/secure
            insertafter: '#### RULES ####'

      - name: "5.1.1.5 | PATCH | Ensure logging is configured | Cron Settings"
        ansible.builtin.blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "#{mark} Cron SETTINGS - CIS benchmark - Ansible-lockdown"
            block: |
              # Cron settings to meet CIS standards
              cron.*                                                   /var/log/cron
            insertafter: '#### RULES ####'

- name: "5.1.1.6 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  when:
      - rhel7cis_rule_5_1_1_6
      - rhel7cis_remote_log_server
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - rule_5.1.1.6
  notify: Restart_rsyslog
  ansible.builtin.blockinfile:
      path: /etc/rsyslog.conf
      state: present
      block: |
        # target can be IP or FQDN
        *.* action(type="omfwd" target="{{ rhel7cis_remote_log_host }}" port="{{ rhel7cis_remote_log_port }}" protocol="{{ rhel7cis_remote_log_protocol }}" action.resumeRetryCount="{{ rhel7cis_remote_log_retrycount }}" queue.type="LinkedList" queue.size="{{ rhel7cis_remote_log_queuesize }}")
      insertafter: EOF
  register: result
  failed_when:
      - result is failed
      - result.rc != 257

- name: "5.1.1.7 | PATCH | Ensure rsyslog is not configured to recieve logs from a remote client"
  when:
      - rhel7cis_rule_5_1_1_7
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - rule_5.1.1.7
  notify: Restart_rsyslog
  block:
      - name: "5.1.1.7 | PATCH | Ensure rsyslog is not configured to recieve logs from a remote client. | When not log host"
        when: not rhel7cis_system_is_log_server
        ansible.builtin.replace:
            path: /etc/rsyslog.conf
            regexp: '{{ item }}'
            replace: '#\1'
        loop:
            - '^(\$ModLoad imtcp)'
            - '^(\$InputTCPServerRun)'
            - '^(module\(load="imtcp"\))'
            - '^(input\(type="imtcp")'

      - name: "5.1.1.7 | PATCH | Ensure rsyslog is not configured to recieve logs from a remote clients. | When log host"
        when: rhel7cis_system_is_log_server
        ansible.builtin.replace:
            path: /etc/rsyslog.conf
            regexp: '^#(.*{{ item }}.*)'
            replace: '\1'
        loop:
            - 'ModLoad imtcp'
            - 'InputTCPServerRun'
