---

- name: "3.4.4.2.1 | PATCH | Ensure iptables loopback traffic is configured"
  when:
      - rhel7cis_rule_3_4_4_2_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.2.1
      - iptables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.2.1 | PATCH | Ensure iptables loopback traffic is configured | INPUT loopback ACCEPT"
        ansible.builtin.iptables:
            action: append
            chain: INPUT
            in_interface: lo
            jump: ACCEPT

      - name: "3.4.4.2.1 | PATCH | Ensure iptables loopback traffic is configured | OUTPUT loopback ACCEPT"
        ansible.builtin.iptables:
            action: append
            chain: OUTPUT
            out_interface: lo
            jump: ACCEPT

      - name: "3.4.4.2.1 | PATCH | Ensure iptables loopback traffic is configured | OUTPUT loopback ACCEPT"
        ansible.builtin.iptables:
            action: append
            chain: INPUT
            source: 127.0.0.0/8
            jump: DROP

- name: "3.4.4.2.2 | PATCH | Ensure iptables outbound and established connections are configured"
  when:
      - rhel7cis_rule_3_4_4_2_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.2.2
      - iptables
      - NIST800-53R5_CA-9
  ansible.builtin.iptables:
      action: append
      chain: '{{ item.chain }}'
      protocol: '{{ item.protocol }}'
      match: state
      ctstate: '{{ item.ctstate }}'
      jump: ACCEPT
  with_items:
      - { chain: OUTPUT, protocol: tcp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: OUTPUT, protocol: udp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: OUTPUT, protocol: icmp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: INPUT, protocol: tcp, ctstate: 'ESTABLISHED' }
      - { chain: INPUT, protocol: udp, ctstate: 'ESTABLISHED' }
      - { chain: INPUT, protocol: icmp, ctstate: 'ESTABLISHED' }

- name: "3.4.4.2.3 | AUDIT | Ensure iptables firewall rules exist for all open ports"
  when:
      - rhel7cis_rule_3_4_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_3.4.4.2.3
      - iptables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.2.3 | AUDIT | Ensure iptables firewall rules exist for all open ports | Get list of open ports"
        ansible.builtin.shell: ss -4tuln
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel7cis_3_4_4_2_3_open_ports

      - name: "3.4.4.2.3 | AUDIT | Ensure iptables firewall rules exist for all open ports | Get list of rules"
        ansible.builtin.shell: iptables -L INPUT -v -n
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel7cis_3_4_4_2_3_current_rules

      - name: "3.4.4.2.3 | AUDIT | Ensure iptables firewall rules exist for all open ports | Alert about settings"
        ansible.builtin.debug:
            msg:
                - "ALERT!!!!Below is the list the open ports and current rules"
                - "Please create a rule for any open port that does not have a current rule"
                - "Open Ports:"
                - "{{ rhel7cis_3_4_4_2_3_open_ports.stdout_lines }}"
                - "Current Rules:"
                - "{{ rhel7cis_3_4_4_2_3_current_rules.stdout_lines }}"

      - name: "3.4.4.2.3 | WARN | Ensure iptables firewall rules exist for all open ports | Warn Count"
        vars:
            warn_control_id: '3.4.4.2.3'
        ansible.builtin.import_tasks:
            file: warning_facts.yml

- name: "3.4.4.2.4 | PATCH | Ensure iptables default deny firewall policy"
  when:
      - rhel7cis_rule_3_4_4_2_4
      - not system_is_ec2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.2.4
      - iptables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.2.4 | PATCH | Ensure iptables default deny firewall policy | Configure SSH to be allowed in"
        ansible.builtin.iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 22
            jump: ACCEPT
            ctstate: 'NEW,ESTABLISHED'

      - name: "3.4.4.2.4 | PATCH | Ensure iptables default deny firewall policy | Configure SSH to be allowed out"
        ansible.builtin.iptables:
            chain: OUTPUT
            protocol: tcp
            source_port: 22
            jump: ACCEPT
            ctstate: 'NEW,ESTABLISHED'

      - name: "3.4.4.2.4 | PATCH | Ensure iptables default deny firewall policy | Enable apt traffic"
        ansible.builtin.iptables:
            chain: INPUT
            ctstate: 'ESTABLISHED'
            jump: ACCEPT

      - name: "3.4.4.2.4 | PATCH | Ensure iptables default deny firewall policy | Set drop items"
        ansible.builtin.iptables:
            policy: DROP
            chain: "{{ item }}"
        with_items:
            - INPUT
            - FORWARD
            - OUTPUT

- name: "3.4.4.2.5 | Ensure iptables rules are saved"
  when:
      - rhel7cis_save_iptables_cis_rules
      - rhel7cis_rule_3_4_4_2_1 or
        rhel7cis_rule_3_4_4_2_2 or
        rhel7cis_rule_3_4_4_2_3 or
        rhel7cis_rule_3_4_4_2_4 or
        rhel7cis_rule_3_4_4_2_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.2.5
      - iptables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.2.5 | Ensure iptables rules are saved "
        ansible.builtin.shell: service iptables save
        changed_when: rhel7cis_iptables_save.rc == 0
        failed_when: rhel7cis_iptables_save.rc != 0
        register: rhel7cis_iptables_save

- name: "3.4.4.2.6 | Ensure iptables service is enabled and running"
  when:
      - rhel7cis_rule_3_4_4_2_6
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.2.6
      - iptables
      - NIST800-53R5_CA-9
  ansible.builtin.service:
      name: iptables
      state: started
      enabled: true
