---

- name: "3.4.4.3.1 | PATCH | Ensure ip6tables loopback traffic is configured"
  when:
      - rhel7cis_rule_3_4_4_3_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.3.1
      - iptables
      - ip6tables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.3.1 | PATCH | Ensure ip6tables loopback traffic is configured | INPUT loopback ACCEPT"
        ansible.builtin.iptables:
            action: append
            chain: INPUT
            in_interface: lo
            jump: ACCEPT
            ip_version: ipv6

      - name: "3.4.4.3.1 | PATCH | Ensure ip6tables loopback traffic is configured | OUTPUT loopback ACCEPT"
        ansible.builtin.iptables:
            action: append
            chain: OUTPUT
            out_interface: lo
            jump: ACCEPT
            ip_version: ipv6

      - name: "3.4.4.3.1 | PATCH | Ensure ip6tables loopback traffic is configured | OUTPUT loopback ACCEPT"
        ansible.builtin.iptables:
            action: append
            chain: INPUT
            source: ::1
            jump: DROP
            ip_version: ipv6

- name: "3.4.4.3.2 | PATCH | Ensure ip6tables outbound and established connections are configured"
  when:
      - rhel7cis_rule_3_4_4_3_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.3.2
      - iptables
      - ip6tables
      - NIST800-53R5_CA-9
  ansible.builtin.iptables:
      action: append
      chain: '{{ item.chain }}'
      protocol: '{{ item.protocol }}'
      match: state
      ctstate: '{{ item.ctstate }}'
      jump: ACCEPT
      ip_version: ipv6
  with_items:
      - { chain: OUTPUT, protocol: tcp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: OUTPUT, protocol: udp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: OUTPUT, protocol: icmp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: INPUT, protocol: tcp, ctstate: 'ESTABLISHED' }
      - { chain: INPUT, protocol: udp, ctstate: 'ESTABLISHED' }
      - { chain: INPUT, protocol: icmp, ctstate: 'ESTABLISHED' }

- name: "3.4.4.3.3 | AUDIT | Ensure ip6tables firewall rules exist for all open ports"
  when:
      - rhel7cis_rule_3_4_4_3_3
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_3.4.4.3.3
      - iptables
      - ip6tables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.3.3 | AUDIT | Ensure ip6tables firewall rules exist for all open ports | Get list of open ports"
        ansible.builtin.command: ss -6tuln
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel7cis_3_4_4_3_3_open_ports

      - name: "3.4.4.3.3 | AUDIT | Ensure ip6tables firewall rules exist for all open ports | Get list of rules"
        ansible.builtin.command: ip6tables -L INPUT -v -n
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel7cis_3_4_4_3_3_current_rules

      - name: "3.4.4.3.3 | AUDIT | Ensure ip6tables firewall rules exist for all open ports | Alert about settings"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below is the list the open ports and current rules"
                - "Please create a rule for any open port that does not have a current rule"
                - "Open Ports:"
                - "{{ rhel7cis_3_4_4_3_3_open_ports.stdout_lines }}"
                - "Current Rules:"
                - "{{ rhel7cis_3_4_4_3_3_current_rules.stdout_lines }}"

      - name: "3.4.4.3.3 | WARN | Ensure ip6tables firewall rules exist for all open ports | Warn Count"
        vars:
            warn_control_id: '3.4.4.3.3'
        ansible.builtin.import_tasks:
            file: warning_facts.yml

- name: "3.4.4.3.4 | PATCH | Ensure ip6tables default deny firewall policy"
  when:
      - rhel7cis_rule_3_4_4_3_4
      - not system_is_ec2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.3.4
      - iptables
      - ip6tables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.3.4 | PATCH | Ensure ip6tables default deny firewall policy | Configure SSH to be allowed in"
        ansible.builtin.iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 22
            jump: ACCEPT
            ctstate: 'NEW,ESTABLISHED'
            ip_version: ipv6

      - name: "3.4.4.3.4 | PATCH | Ensure ip6tables default deny firewall policy | Configure SSH to be allowed out"
        ansible.builtin.iptables:
            chain: OUTPUT
            protocol: tcp
            source_port: 22
            jump: ACCEPT
            ctstate: 'NEW,ESTABLISHED'
            ip_version: ipv6

      - name: "3.4.4.3.4 | PATCH | Ensure ip6tables default deny firewall policy | Enable apt traffic"
        ansible.builtin.iptables:
            chain: INPUT
            ctstate: 'ESTABLISHED'
            jump: ACCEPT
            ip_version: ipv6

      - name: "3.4.4.3.4 | PATCH | Ensure ip6tables default deny firewall policy | Set drop items"
        ansible.builtin.iptables:
            policy: DROP
            chain: "{{ item }}"
            ip_version: ipv6
        with_items:
            - INPUT
            - FORWARD
            - OUTPUT

- name: "3.4.4.3.5 | Ensure ip6tables rules are saved"
  when:
      - rhel7cis_save_ip6tables_cis_rules
      - rhel7cis_rule_3_4_4_3_1 or
        rhel7cis_rule_3_4_4_3_2 or
        rhel7cis_rule_3_4_4_3_3 or
        rhel7cis_rule_3_4_4_3_4 or
        rhel7cis_rule_3_4_4_3_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.3.5
      - iptables
      - ip6tables
      - NIST800-53R5_CA-9
  block:
      - name: "3.4.4.3.5 | Ensure ip6tables rules are saved "
        ansible.builtin.shell: service ip6tables save
        changed_when: rhel7cis_ip6tables_save.rc == 0
        failed_when: rhel7cis_ip6tables_save.rc != 0
        register: rhel7cis_ip6tables_save

- name: "3.4.4.3.6 | Ensure ip6tables is enabled and running"
  when:
      - rhel7cis_rule_3_4_4_3_6
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.3.6
      - iptables
      - ip6tables
      - NIST800-53R5_CA-9
  ansible.builtin.service:
      name: ip6tables
      state: started
      enabled: true
