---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: CIS-centos7
    image: milcom/centos7-systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
#    - side_effect
    - verify
    - cleanup
    - destroy
