---

- name: "2.1.1 | PATCH | Ensure xinetd is not installed"
  package:
      name: xinetd
      state: absent
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - ("'xinetd' in ansible_facts.packages") and not rhel7cis_xinetd_required
      - rhel7cis_rule_2_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.1
