---

- name: "1.6.1.1 | PATCH | Ensure SELinux is installed"
  ansible.builtin.package:
      name: libselinux
      state: present
  when:
      - not rhel7cis_selinux_disable
      - rhel7cis_rule_1_6_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.6.1.1
  vars:
      ansible_python_interpreter: /bin/python

- name: "1.6.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  ansible.builtin.replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
  register: selinux_grub_patch
  ignore_errors: true  # noqa ignore-errors
  notify:
      - grub2cfg
      - reboot_required
  when:
      - not rhel7cis_selinux_disable
      - rhel7cis_rule_1_6_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.6.1.2

- name: "1.6.1.3 | PATCH | Ensure SELinux policy is configured\n
         1.6.1.4 | PATCH | Ensure the SELinux state is enforcing or permissive"
  ansible.posix.selinux:
      conf: /etc/selinux/config
      policy: "{{ rhel7cis_selinux_pol }}"
      state: "{{ rhel7cis_selinux_state }}"
  when:
      - not rhel7cis_selinux_disable
      - rhel7cis_rule_1_6_1_3
      - rhel7cis_rule_1_6_1_4
  tags:
      - level1-server
      - level1-workstation
      - selinux
      - patch
      - rule_1.6.1.3
      - rule_1.6.1.4

- name: "1.6.1.5 | PATCH | Ensure the SELinux state is enforcing"
  ansible.posix.selinux:
      conf: /etc/selinux/config
      policy: "{{ rhel7cis_selinux_pol }}"
      state: enforcing
  when:
      - not rhel7cis_selinux_disable
      - not rhel7cis_selinux_state == "permissive"
      - rhel7cis_rule_1_6_1_5
  tags:
      - level2-server
      - level2-workstation
      - selinux
      - patch
      - rule_1.6.1.5

- name: "1.6.1.6 | AUDIT | Ensure no unconfined daemons exist"
  block:
      - name: "1.6.1.6 | AUDIT | Ensure no unconfined daemons exist | Find the unconfined daemons"
        ansible.builtin.shell: ps -eZ | egrep "initrc" | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
        failed_when: false
        changed_when: false
        check_mode: false
        register: rhelcis_1_6_1_6_unconf_daemons

      - name: "1.6.1.6 | AUDIT | Ensure no unconfined daemons exist | Message on no unconfined daemones"
        ansible.builtin.debug:
            msg: "Good News! There are no unconfined daemons found on your system"
        when: rhelcis_1_6_1_6_unconf_daemons.stdout | length == 0

      - name: "1.6.1.6 | AUDIT | Ensure no unconfined daemons exist | Message on unconfined daemones"
        ansible.builtin.debug:
            msg: "WARNING!! You have unconfined daemons: {{ rhelcis_1_6_1_6_unconf_daemons.stdout_lines }}"
        when: rhelcis_1_6_1_6_unconf_daemons.stdout | length > 0
  when:
      - rhel7cis_rule_1_6_1_6
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_1.6.1.6

- name: "1.6.1.7 | PATCH | Ensure SETroubleshoot is not installed"
  ansible.builtin.package:
      name: setroubleshoot
      state: absent
  when:
      - rhel7cis_rule_1_6_1_7
  tags:
      - level1-server
      - level1-workstation
      - selinux
      - patch
      - rule_1.6.1.7
  vars:
      ansible_python_interpreter: /bin/python

- name: "1.6.1.8 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  ansible.builtin.package:
      name: mcstrans
      state: absent
  when:
      - rhel7cis_rule_1_6_1_8
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.6.1.8
  vars:
      ansible_python_interpreter: /bin/python
