---

- name: "1.1.2.1.1 | PATCH | Ensure /tmp is a separate partition"
  when:
      - rhel7cis_rule_1_1_2_1_1
      - "'/tmp' not in mount_names"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - mounts
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - rule_1.1.2.1.1
  vars:
      warn_control_id: '1.1.2.1.1'
      required_mount: '/tmp'
  block:
      - name: "1.1.2.1.1 | PATCH | Ensure /tmp is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} is not mounted on a separate partition"

      - name: "1.1.2.1.1 | PATCH | Ensure /tmp is a separate partition | Present"
        ansible.builtin.import_tasks:
            file: warning_facts.yml

# via fstab
- name: |
        "1.1.2.1.2 | PATCH | Ensure nodev option set on /tmp partition"
        "1.1.2.1.3 | PATCH | Ensure nosuid option set on /tmp partition"
        "1.1.2.1.4 | PATCH | Ensure noexec option set on /tmp partition"
  when:
      - item.mount == "/tmp"
      - rhel7cis_rule_1_1_2_1_2 or
        rhel7cis_rule_1_1_2_1_3 or
        rhel7cis_rule_1_1_2_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - rule_1.1.2.1.2
      - rule_1.1.2.1.3
      - rule_1.1.2.1.4
  ansible.posix.mount:
      name: /tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel7cis_rule_1_1_2_1_2 %}nodev,{% endif %}{% if rhel7cis_rule_1_1_2_1_3 %}nosuid,{% endif %}{% if rhel7cis_rule_1_1_2_1_4 %}noexec{% endif %}
  notify: Remount_tmp
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
