---

- name: "1.2.1 | L1 | PATCH | Ensure GPG keys are configured"
  block:
      - name: "1.2.1 | L1 | PATCH | Ensure GPG keys are configured | RedHat"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
        when:
            - ansible_distribution == "RedHat"

      - name: "1.2.1 | L1 | PATCH | Ensure GPG keys are configured | CentOS"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
        when:
            - ansible_distribution == "CentOS"
  when:
      - rhel7cis_rule_1_2_1
  tags:
      - level1
      - patch
      - rule_1.2.1

- name: "1.2.2 | L1 | AUDIT | Ensure package manager repositories are configured"
  block:
      - name: "1.2.2 | L1 | AUDIT | Ensure package manager repositories are configured"
        shell: yum repolist
        changed_when: false
        register: repolist
        check_mode: false
        args:
            warn: false
        tags:
            - skip_ansible_lint

      - name: "1.2.2 | L1 | AUDIT | Ensure package manager repositories are configured"
        debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
  when:
      - rhel7cis_rule_1_2_2
  tags:
      - level1
      - audit
      - rule_1.2.2
      - skip_ansible_lint

- name: "1.2.3 | L1 | PATCH | Ensure gpgcheck is globally activated"
  block:
      - name: "1.2.3 | L1 | AUDIT | Ensure gpgcheck is globally activated"
        find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        changed_when: false
        register: yum_repos

      - name: "1.2.3 | L1 | PATCH | Ensure gpgcheck is globally activated"
        replace:
            path: "{{ item.path }}"
            regexp: "^gpgcheck=0"
            replace: "gpgcheck=1"
        loop: "{{ yum_repos.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rhel7cis_rule_1_2_3
  tags:
      - level1
      - patch
      - rule_1.2.3


- name: "1.2.4 | L1 | AUDIT | Ensure Red Hat Subscription Manager connection is configured"
  shell: subscription-manager identity
  changed_when: false
  failed_when: false
  when:
      - ansible_distribution == "RedHat"
      - rhel7cis_rule_1_2_4
  tags:
      - level1
      - patch
      - rule_1.2.4
      - skip_ansible_lint

- name: "1.2.5 | L1 | PATCH | Disable the rhnsd Daemon"
  service:
      name: rhnsd
      state: stopped
      enabled: no
      masked: true
  when:
      - ansible_distribution == "RedHat" and not rhel7cis_rhnsd_required
      - rhel7cis_rule_1_2_5
  tags:
      - level1
      - patch
      - rule_1.2.5
