---

- name: "1.4.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  when:
      - rhel7cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - sysctl
      - NIST800-53R5_CM-6
      - rule_1.4.1
  ansible.posix.sysctl:
      name: kernel.randomize_va_space
      value: '2'
      reload: true
      sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf
      sysctl_set: true
      ignoreerrors: true

- name: "1.4.2 | PATCH | Ensure ptrace_scope is restricted"
  when:
      - rhel7cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - sysctl
      - NIST800-53R5_CM-6
      - rule_1.4.2
  ansible.posix.sysctl:
      name: kernel.yama.ptrace_scope
      value: '1'
      reload: true
      sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf
      sysctl_set: true
      ignoreerrors: true

- name: "1.4.3 | PATCH | Ensure core dump backtraces are disabled"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - sysctl
      - NIST800-53R5_CM-6
      - rule_1.4.3
  ansible.builtin.lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: 'ProcessSizeMax='
      line: 'ProcessSizeMax=0'
  when:
      - rhel7cis_rule_1_4_3

- name: "1.4.4 | PATCH | Ensure core dump storage is disabled"
  when:
      - rhel7cis_rule_1_4_4
      - systemd_coredump.stat.exists
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.4
  notify: Systemd_daemon_reload
  ansible.builtin.lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: 'Storage='
      line: 'Storage=none'
