---

- name: "1.1.2.7.1 | AUDIT | Ensure /var/log/audit is a seperate partition"
  when:
      - required_mount not in mount_names
      - rhel7cis_rule_1_1_2_7_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.2.7.1
      - mounts
      - NIST800-53R5_CM-7
  vars:
      warn_control_id: '1.1.2.7.1'
      required_mount: '/var/log/audit'
  block:
      - name: "1.1.2.7.1 | AUDIT | Ensure /var/log/audit is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.2.7.1 | AUDIT | Ensure /var/log/audit is a separate partition | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml

- name: |
         "1.1.2.7.2 | PATCH | Ensure nodev option set on /var/log/audit partition
          1.1.2.7.3 | PATCH | Ensure nosuid option set on /var/log/audit partition
          1.1.2.7.4 | PATCH | Ensure noexec option set on /var/log/audit partition"
  when:
      - item.mount == "/var/log/audit"
      - rhel7cis_tmp_svc
      - rhel7cis_rule_1_1_2_7_2 or
        rhel7cis_rule_1_1_2_7_3 or
        rhel7cis_rule_1_1_2_7_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.2.7.2
      - rule_1.1.2.7.3
      - rule_1.1.2.7.4
      - mounts
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  ansible.posix.mount:
      name: /var/log/audit
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel7cis_rule_1_1_2_7_2 %}nodev,{% endif %}{% if rhel7cis_rule_1_1_2_7_3 %}nosuid,{% endif %}{% if rhel7cis_rule_1_1_2_7_4 %}noexec{% endif %}
  notify: Remount_var_log_audit
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
