---

- name: "1.1.2.6.1 | AUDIT | Ensure separate partition exists for /var/log"
  when:
      - rhel7cis_rule_1_1_2_6_1
      - "'/var/log' not in mount_names"
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.2.6.1
      - NIST800-53R5_CM-7
  vars:
      warn_control_id: '1.1.2.6.1'
      required_mount: '/var/log'
  block:
      - name: "1.1.2.6.1 | AUDIT | Ensure separate partition exists for /var/log | Warn if partition is absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"
        register: var_log_mount_absent
        changed_when: var_log_mount_absent.skipped is undefined

      - name: "1.1.2.6.1 | AUDIT | Ensure separate partition exists for /var/log | Present"
        ansible.builtin.import_tasks:
            file: warning_facts.yml

# skips if mount is absent
- name: |
          "1.1.2.6.2 | PATCH | Ensure nodev option set on /var/log partition"
          "1.1.2.6.3 | PATCH | Ensure nosuid option set on /var/log partition"
          "1.1.2.6.4 | PATCH | Ensure noexec option set on /var/log partition"
  when:
      - "'/var/log' in mount_names"
      - item.mount == "/var/log"
      - rhel7cis_rule_1_1_2_6_2 or
        rhel7cis_rule_1_1_2_6_3 or
        rhel7cis_rule_1_1_2_6_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - skip_ansible_lint
      - rule_1.1.2.6.2
      - rule_1.1.2.6.3
      - rule_1.1.2.6.4
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  notify: Change_requires_reboot
  ansible.posix.mount:
      name: /var/log
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel7cis_rule_1_1_2_6_2 %}nodev,{% endif %}{% if rhel7cis_rule_1_1_2_6_3 %}nosuid,{% endif %}{% if rhel7cis_rule_1_1_2_6_4 %}noexec{% endif %}
  loop: "{{ ansible_facts.mounts }}"
  loop_control:
      label: "{{ item.device }}"
