---

- name: "4.2.2.1 | PATCH | Ensure journald is configured to send logs to rsyslog"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^[F|f]orward[T|t]o[S|s]yslog='
      line: "ForwardToSyslog=yes"
  when:
      - rhel7cis_rule_4_2_2_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.2.1
      - journald

- name: "4.2.2.2 | PATCH | Ensure journald is configured to compress large log files"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^[C|c]ompress='
      line: "Compress=yes"
  when:
      - rhel7cis_rule_4_2_2_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.2.2
      - journald

- name: "4.2.2.3 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^[S|s]torage='
      line: "Storage=persistent"
  when:
      - rhel7cis_rule_4_2_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.2.3
      - journald
